In [7]:
# import dependencies
import pandas as pd
import glob
import matplotlib.pyplot as plt
import numpy as np 
from pandas_geojson import to_geojson

ModuleNotFoundError: No module named 'pandas_geojson'

In [2]:
# load in data
cases_data = pd.read_csv("data/cleaned/confirmed_covid_cases_cleaned.csv")
cases_data

,state,state_abv,state_id,date,cases,population,cases_per_cap
0,Alabama,AL,1,2020-01-22,0,5031864,0.000000
1,Alabama,AL,1,2020-01-23,0,5031864,0.000000
2,Alabama,AL,1,2020-01-24,0,5031864,0.000000
3,Alabama,AL,1,2020-01-25,0,5031864,0.000000
4,Alabama,AL,1,2020-01-26,0,5031864,0.000000
...,...,...,...,...,...,...,...
64511,District of Columbia,DC,51,2023-07-19,169149,21591299,0.007834
64512,District of Columbia,DC,51,2023-07-20,169149,21591299,0.007834
64513,District of Columbia,DC,51,2023-07-21,169149,21591299,0.007834
64514,District of Columbia,DC,51,2023-07-22,169149,21591299,0.007834
64515,District of Columbia,DC,51,2023-07-23,169149,21591299,0.007834

In [8]:
# check data types
cases_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64516 entries, 0 to 64515
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          64516 non-null  object
 1   state_abv      64516 non-null  object
 2   state_id       64516 non-null  int64
 3   date           64516 non-null  object
 4   cases          64516 non-null  int64
 5   population     64516 non-null  int64
 6   cases_per_cap  64516 non-null  float64
dtypes: float64(1), int64(3), object(3)
memory usage: 3.4+ MB

In [3]:
# rearrange in a df
df = pd.DataFrame({
    "state_id" : cases_data["state_id"],
    "state_abv" : cases_data["state_abv"],
    "state" : cases_data["state"],
    "date" : cases_data["date"],
    "cases" : cases_data["cases"],
    "population" : cases_data["population"],
    "cases_per_cap" : cases_data["cases_per_cap"]
})
df

,state_id,state_abv,state,date,cases,population,cases_per_cap
0,1,AL,Alabama,2020-01-22,0,5031864,0.000000
1,1,AL,Alabama,2020-01-23,0,5031864,0.000000
2,1,AL,Alabama,2020-01-24,0,5031864,0.000000
3,1,AL,Alabama,2020-01-25,0,5031864,0.000000
4,1,AL,Alabama,2020-01-26,0,5031864,0.000000
...,...,...,...,...,...,...,...
64511,51,DC,District of Columbia,2023-07-19,169149,21591299,0.007834
64512,51,DC,District of Columbia,2023-07-20,169149,21591299,0.007834
64513,51,DC,District of Columbia,2023-07-21,169149,21591299,0.007834
64514,51,DC,District of Columbia,2023-07-22,169149,21591299,0.007834
64515,51,DC,District of Columbia,2023-07-23,169149,21591299,0.007834

In [5]:
# convert date to datetime format
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64516 entries, 0 to 64515
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state_id       64516 non-null  int64
 1   state_abv      64516 non-null  object
 2   state          64516 non-null  object
 3   date           64516 non-null  datetime64[ns]
 4   cases          64516 non-null  int64
 5   population     64516 non-null  int64
 6   cases_per_cap  64516 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 3.4+ MB

In [6]:
# export to a json file
df.to_geojson("data/cleaned/cases.geojson")

AttributeError: 'DataFrame' object has no attribute 'to_geojson'

In [31]:
# drop 2022 and 2023
df2 = df[(df['date'].dt.year < 2022) | (df['date'].dt.year > 2023)]

In [32]:
df2

,state_id,state_abv,state,date,cases,population,cases_per_cap
0,1,AL,Alabama,2020-01-22,0,5031864,0.000000
1,1,AL,Alabama,2020-01-23,0,5031864,0.000000
2,1,AL,Alabama,2020-01-24,0,5031864,0.000000
3,1,AL,Alabama,2020-01-25,0,5031864,0.000000
4,1,AL,Alabama,2020-01-26,0,5031864,0.000000
...,...,...,...,...,...,...,...
63956,51,DC,District of Columbia,2021-12-27,88765,21591299,0.004111
63957,51,DC,District of Columbia,2021-12-28,90633,21591299,0.004198
63958,51,DC,District of Columbia,2021-12-29,92045,21591299,0.004263
63959,51,DC,District of Columbia,2021-12-30,94286,21591299,0.004367
63960,51,DC,District of Columbia,2021-12-31,94286,21591299,0.004367

In [33]:
df2.to_csv("data/cleaned/confirmed_covid_cases_2020_2021.csv")
df2.to_json("data/cleaned/cases_2020_2021.json")

In [10]:
vaccinations_data = pd.read_csv("data/reference/COVID-19_Vaccinations_in_the_United_States_Jurisdiction_20240104.csv")
vaccinations_data

,date,MMWR_week,state_abv,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Novavax,Distributed_Unk_Manuf,Dist_Per_100K,...,Dist_Bivalent_PFR,Dist_Bivalent_MOD,Bivalent_Booster_5Plus,Bivalent_Booster_5Plus_Pop_Pct,Bivalent_Booster_12Plus,Bivalent_Booster_12Plus_Pop_Pct,Bivalent_Booster_18Plus,Bivalent_Booster_18Plus_Pop_Pct,Bivalent_Booster_65Plus,Bivalent_Booster_65Plus_Pop_Pct
0,2020-12-14,51.0,AK,4875.0,0.0,0.0,0.0,NaN,0.0,666.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-12-15,51.0,AK,12675.0,0.0,0.0,0.0,NaN,0.0,1733.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-12-16,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-12-17,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-12-18,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38483,2023-04-12,15.0,WY,1274595.0,49300.0,490040.0,585145.0,3300.0,0.0,220229.0,...,98570.0,48240.0,64704.0,11.9,63730.0,13.0,62116.0,14.0,34203.0,34.5
38484,2023-04-19,16.0,WY,1276035.0,49300.0,490040.0,585605.0,3600.0,0.0,220478.0,...,99050.0,48440.0,64747.0,11.9,63775.0,13.0,62146.0,14.0,34171.0,34.5
38485,2023-04-26,17.0,WY,1277235.0,49300.0,490040.0,585605.0,3600.0,0.0,220685.0,...,99630.0,49060.0,65007.0,12.0,64027.0,13.0,62391.0,14.0,34285.0,34.6
38486,2023-05-03,18.0,WY,1279735.0,49300.0,490040.0,585605.0,3600.0,0.0,221117.0,...,101190.0,50000.0,65090.0,12.0,64107.0,13.1,62464.0,14.0,34327.0,34.6
38487,2023-05-10,19.0,WY,1281755.0,49300.0,490040.0,585605.0,3700.0,0.0,221466.0,...,102510.0,50600.0,65920.0,12.1,64919.0,13.2,63244.0,14.2,34832.0,35.1

In [12]:
vaccinations_data["date"] = pd.to_datetime(vaccinations_data["date"])

In [13]:
vaccinations_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38488 entries, 0 to 38487
Columns: 109 entries, date to Bivalent_Booster_65Plus_Pop_Pct
dtypes: datetime64[ns](1), float64(107), object(1)
memory usage: 32.0+ MB

In [14]:
vaccinations_data.to_json("data/cleaned/vaccinations")

In [16]:
vaccinations_df = vaccinations_data[(vaccinations_data['date'].dt.year < 2022) | (vaccinations_data['date'].dt.year > 2023)]

In [17]:
vaccinations_df

,date,MMWR_week,state_abv,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Novavax,Distributed_Unk_Manuf,Dist_Per_100K,...,Dist_Bivalent_PFR,Dist_Bivalent_MOD,Bivalent_Booster_5Plus,Bivalent_Booster_5Plus_Pop_Pct,Bivalent_Booster_12Plus,Bivalent_Booster_12Plus_Pop_Pct,Bivalent_Booster_18Plus,Bivalent_Booster_18Plus_Pop_Pct,Bivalent_Booster_65Plus,Bivalent_Booster_65Plus_Pop_Pct
0,2020-12-14,51.0,AK,4875.0,0.0,0.0,0.0,NaN,0.0,666.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-12-15,51.0,AK,12675.0,0.0,0.0,0.0,NaN,0.0,1733.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-12-16,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-12-17,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-12-18,51.0,AK,26325.0,0.0,0.0,0.0,NaN,0.0,3599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38269,2021-12-27,52.0,WY,846065.0,46500.0,359420.0,440145.0,NaN,0.0,146186.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38270,2021-12-28,52.0,WY,846065.0,46500.0,359420.0,440145.0,NaN,0.0,146186.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38271,2021-12-29,52.0,WY,846565.0,46500.0,359820.0,440245.0,NaN,0.0,146272.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38272,2021-12-30,52.0,WY,845705.0,46700.0,358760.0,440245.0,NaN,0.0,146124.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38273,2021-12-31,52.0,WY,846205.0,46700.0,359260.0,440245.0,NaN,0.0,146210.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
vaccinations_df.to_json("data/cleaned/vaccinations_2020_2021")